site_name: Warehouse Management Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Project Overview: project-overview.md
  - Requirements:
      - Functional Requirements: functional-requirements.md
      - Non-Functional Requirements: non-functional-requirements.md
  - Architecture: architecture.md
  - Business Logic: business-logic.md
  - Database Model: database.md
  - UI Design: ui-design.md
  - Use Case Diagram: use-case.md